version: "3.8"

services:
  tts-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: tts-api
    volumes:
      - ./.env:/app/.env
    ports:
      - "8000:8000"
    environment:
      - LOCAL_MODEL_DIR=/app/models/xtts_v2
      - USE_DEEPSPEED=${USE_DEEPSPEED}
      - USE_CUDA=${USE_CUDA}
      - CACHE_MAX_SIZE=${CACHE_MAX_SIZE}
      - USE_S3=${USE_S3}
      - S3_BUCKET=${S3_BUCKET}
      - S3_MODEL_PATH=${S3_MODEL_PATH}
      - SPACES_KEY=${SPACES_KEY}
      - SPACES_SECRET=${SPACES_SECRET}
      - DO_REGION=${DO_REGION}
      - DO_ENDPOINT_URL=${DO_ENDPOINT_URL}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
